src/MyBudget/MyBudget.Web.AspNet/Models/Budgets.cs
using MyBudget.Domain.ValueObjects;
using MyBudget.Projections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyBudget.Web.AspNet.Models
{
    public class BudgetListViewModel
    {
        public IEnumerable<Budget> Budgets { get; private set; }

        public BudgetListViewModel(IEnumerable<Budget> budgets)
        {
            Budgets = budgets;
        }

    
    }

    public class CreateBudgetViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Currency> Currencies { get; set; }
        public string CurrencyISOCode { get; set; }


        public IEnumerable<System.Web.Mvc.SelectListItem> GetCurrencies()
        {
            return Currencies.Select(c => new System.Web.Mvc.SelectListItem
            {
                Value = c.IsoCode,
                Text = c.Name,
                Selected = string.Compare(c.IsoCode, CurrencyISOCode, true) == 0
            }).ToList();
        }
    }


    public class BudgetDetailsViewModel
    {
        public Budget Budget { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<string> DistributionKeys { get; set; }
 
    }

    public class KeyAmount
    {
        public string DistributionKey { get; set; }
        public decimal Amount { get; set; }
    }

}

src/MyBudget/MyBudget.Web.AspNet/Controllers/BudgetsController.cs
using MyBudget.Commands;
using MyBudget.Domain.Budgets;
using MyBudget.Web.AspNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBudget.Web.AspNet.Controllers
{
    public partial class BudgetsController : MyBudgetController
    {
        public virtual ActionResult Index()
        {
            var budgets = ProjectionManager.GetBudgetsList().GetBudgetsUserCanView(GetCurrentUserId());

            var model = new BudgetListViewModel(budgets);

            return View(model);
        }

        public virtual ActionResult Details(string id)
        {
            var budgetId = new BudgetId(id);
            var budget = ProjectionManager.GetBudgetsList().GetBudgetById(budgetId);
            var categories = ProjectionManager.GetCategories().GetBudgetsCategories(budgetId);
           
            var model = new BudgetDetailsViewModel
            {
                Budget = budget,
                Categories = categories,
                DistributionKeys = budget.GetDistributionKeys(),
            };
            return View(model);
        }


        public virtual ActionResult Create()
        {
            var model = new CreateBudgetViewModel
            {
                Id = BudgetId.Create().ToString(),
                Name = "New Budget",
                Currencies = MyBudget.Domain.ValueObjects.Currencies.GetAll(),
            };
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Create(CreateBudgetViewModel model)
        {
            try
            {
                var handler = CommandManager.Create<CreateBudget>();
                handler(new CreateBudget
                {
                    UserId = GetCurrentUserId().ToString(),
                    BudgetName = model.Name,
                    BudgetId = BudgetId.Create().ToString(),
                    CurrencyISOCode = model.CurrencyISOCode,

                    Id = Guid.NewGuid(),
                    Timestamp = DateTime.Now,
                });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public virtual ActionResult Edit(int id)
        {
            //var model = new BudgetViewModel
            //{

            //};
            return View();
        }

        [HttpPost]
        public virtual ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public virtual ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public virtual ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }

}

src/MyBudget/MyBudget.Web.AspNet/Controllers/LinesController.cs
using MyBudget.Commands;
using MyBudget.Domain.Lines;
using MyBudget.Domain.ValueObjects;
using MyBudget.Web.AspNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBudget.Web.AspNet.Controllers
{
    public partial class LinesController : MyBudgetController
    {

        public virtual ActionResult Index(string id)
        {
            var readModel = ProjectionManager.GetBudgetLinesProjection(id);
            var lines = readModel.GetAllLines();
            var model = new BudgetLinesViewModel(id, lines);

            return View(model);
        }

        public virtual ActionResult Page(string id, string From, string To, int? pageIndex, string category)
        {
            DateTime? from = null;
            DateTime? to = null;

            if (string.IsNullOrEmpty(From) == false)
                from = DateTime.Parse(From);

            if (string.IsNullOrEmpty(To) == false)
                to = DateTime.Parse(To);

            var categories = ProjectionManager.GetCategories().GetBudgetsCategories(new Domain.Budgets.BudgetId(id));
            var readModel = ProjectionManager.GetBudgetLinesProjection(id);
            var lines = readModel.GetAllLinesPaged(pageIndex.GetValueOrDefault(), from, to, category);

            var model = new BudgetLinesPagedViewModel(id, lines, from, to, categories, category);

            return View(model);
        }

        public virtual ActionResult Details(int id)
        {
            return View();
        }

        public virtual ActionResult Create(string id)
        {
            var model = Prepare_EditBudgetLineViewModel(id);
            
            return View(Views.Edit, model);
        }

        [HttpPost]
        public virtual ActionResult Create(EditBudgetLineViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var handler = CommandManager.Create<CreateLine>();
                    handler(model.PrepareCreateLine(GetCurrentUserId().ToString()));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("CurrencyISOCode", ex.Message);
                }
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction(Actions.Index(model.BudgetId));
            }
            else
            {
                var newmodel = Prepare_EditBudgetLineViewModel(model.BudgetId);
  
                newmodel.LoadUserInputFrom(model);

                return View(Views.Edit, newmodel);
            }
        }

        EditBudgetLineViewModel Prepare_EditBudgetLineViewModel(string id)
        {
            var categories = ProjectionManager.GetCategories().GetBudgetsCategories(new Domain.Budgets.BudgetId(id));
            var budget = ProjectionManager.GetBudgetsList().GetBudgetById(new Domain.Budgets.BudgetId(id));

            var model = new EditBudgetLineViewModel(budget.Name, id, budget.CurrencyISOCode, categories, budget.GetDistributionKeys(),
                Currencies.GetAll());
            return model;
        }

        public virtual ActionResult Edit(string budgetId, string lineId)
        {
            var categories = ProjectionManager.GetCategories().GetBudgetsCategories(new Domain.Budgets.BudgetId(budgetId));
            var budget = ProjectionManager.GetBudgetsList().GetBudgetById(new Domain.Budgets.BudgetId(budgetId));

            var model = new EditBudgetLineViewModel(budget.Name, budget.Id, budget.CurrencyISOCode, ProjectionManager.GetStreamEvents(lineId), categories, budget.GetDistributionKeys(), Currencies.GetAll());

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Edit(EditBudgetLineViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var handler = CommandManager.Create<UpdateLine>();
                    handler(model.PrepareUpdateLine(GetCurrentUserId().ToString()));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction(Actions.Index(model.BudgetId));
            }
            else
            {
                var newmodel = Prepare_EditBudgetLineViewModel(model.BudgetId);

                newmodel.LoadUserInputFrom(model);

                return View(newmodel);
            }
        }


        public virtual ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public virtual ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }

}

src/MyBudget/MyBudget.Web.AspNet/Views/Budgets/Create.cshtml
@model MyBudget.Web.AspNet.Models.CreateBudgetViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Budgets", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BudgetViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyISOCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(f => f.CurrencyISOCode, Model.GetCurrencies())
                @Html.ValidationMessageFor(model => model.CurrencyISOCode)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/MyBudget/MyBudget.Web.AspNet/Views/Budgets/Details.cshtml
@model MyBudget.Web.AspNet.Models.BudgetDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Budget</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Budget.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Budget.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Budget.CurrencyISOCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Budget.CurrencyISOCode)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Budget.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Budget.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Budget.OwnerUsername)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Budget.OwnerUsername)
        </dd>

        <dt>
            Categories
        </dt>
        <dd>
            @foreach (var category in Model.Categories)
            {
                <span><a href="@Url.Action(MVC.Category.Edit(Model.Budget.Id, category.Id))">@category.Name</a></span>
            }
        </dd>
        <dt>
            DistributionKeys
        </dt>
        <dd>
            @foreach (var dk in Model.DistributionKeys)
            {
                <span><a >@dk</a></span>
            }
        </dd>
    </dl>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Budget.Id }) |
    @Html.ActionLink("Add Category", MVC.Category.Actions.Create(Model.Budget.Id)) |
    @Html.ActionLink("Add Distribution Key", MVC.DistributionKey.Actions.Create(Model.Budget.Id,
    Url.Action(MVC.Budgets.Details(Model.Budget.Id)))) |

    @Html.ActionLink("Back to List", "Index")


</p>

src/MyBudget/MyBudget.Web.AspNet/Views/Budgets/Index.cshtml
@model MyBudget.Web.AspNet.Models.BudgetListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">


@foreach (var item in Model.Budgets) {
    <tr>
        <td>
            @item.Name
        </td>
        <td>
            @item.Created
        </td>
        <td>
            @item.OwnerUsername
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Stats", MVC.BudgetStats.Index(item.Id)) |
            @Html.ActionLink("Lines", MVC.Lines.Page(item.Id, null, null, null,null)) |
            @*@Html.ActionLink("Lines", "Index", "Lines", new { id = item.Id }, new object()) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

src/MyBudget/MyBudget.Web.AspNet/Views/Budgets/Lines.cshtml
@model MyBudget.Web.AspNet.Models.BudgetLinesViewModel 

@{
    ViewBag.Title = "Lines";
}

<h2>Lines</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Inserito
        </th>
        <th>
            Accaduto
        </th>
        <th>
            Categoria
        </th>
        <th>
            Descrizione
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Lines) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Timestamp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>